//
//  RNDBindingConstants.h
//  RNDKit
//
//  Created by Erikheath Thomas on 10/20/17.
//  Copyright © 2017 Curated Cocoa LLC. All rights reserved.
//

#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

FOUNDATION_EXPORT NSString * const RNDKitErrorDomain;

typedef NS_ENUM(NSUInteger, RNDBindingProcessorErrorCode) {
    RNDObservedObjectNotFound = 1,
    RNDObservedObjectIsNil = 2,
    RNDProcessorIsNotRegisteredAsObserver = 3,
    RNDExceptionAsError = 4,
    RNDObjectIsBoundError = 5,
    RNDAttemptToObserveProcessorError = 6,
    RNDKeyValuePathError = 7
};

typedef NSString * const RNDKitErrorKey;
FOUNDATION_EXPORT RNDKitErrorKey RNDBindingFailedErrorKey;
FOUNDATION_EXPORT RNDKitErrorKey RNDObservedObjectNotFoundErrorKey;
FOUNDATION_EXPORT RNDKitErrorKey RNDBindingIdentifierRecoverySuggestionErrorKey;
FOUNDATION_EXPORT RNDKitErrorKey RNDMonitorObservedObjectErrorKey;
FOUNDATION_EXPORT RNDKitErrorKey RNDObservedObjectIsNilErrorKey;
FOUNDATION_EXPORT RNDKitErrorKey RNDObserverObjectIsNilErrorKey;
FOUNDATION_EXPORT RNDKitErrorKey RNDMonitorObservedObjectRecoverySuggestionErrorKey;
FOUNDATION_EXPORT RNDKitErrorKey RNDMonitorObserverObjectRecoverySuggestionErrorKey;
FOUNDATION_EXPORT RNDKitErrorKey RNDKeyPathIsNilErrorKey;
FOUNDATION_EXPORT RNDKitErrorKey RNDUnbindingErrorKey;
FOUNDATION_EXPORT RNDKitErrorKey RNDUnbindingUnregistrationErrorKey;
FOUNDATION_EXPORT RNDKitErrorKey RNDUnbindingExceptionRecoverySuggestionErrorKey;
FOUNDATION_EXPORT RNDKitErrorKey RNDUnderlyingErrorsArrayKey;
FOUNDATION_EXPORT RNDKitErrorKey RNDObjectIsBoundErrorKey;
FOUNDATION_EXPORT RNDKitErrorKey RNDObjectIsBoundRecoverySuggestionErrorKey;

#pragma mark - RNDBinderManifestKeys
typedef NSString * const RNDBinderManifestKey;
typedef NSString * const RNDBinderSetKey;
FOUNDATION_EXPORT RNDBinderManifestKey RNDBinderManifestNamespaceKey;
FOUNDATION_EXPORT RNDBinderManifestKey RNDBinderManifestLocationKey;
FOUNDATION_EXPORT RNDBinderManifestKey RNDBinderManifestBinderSetURLKey;

#pragma mark - RNDBindingType
typedef NSString * const RNDBindingType;
FOUNDATION_EXPORT RNDBindingType RNDEntityType;
FOUNDATION_EXPORT RNDBindingType RNDClassType;
FOUNDATION_EXPORT RNDBindingType RNDResourceType;

#pragma mark - RNDArgumentNames
typedef NSString * const RNDArgument NS_STRING_ENUM;
FOUNDATION_EXPORT RNDArgument RNDEventArgument;
FOUNDATION_EXPORT RNDArgument RNDSenderArgument;
FOUNDATION_EXPORT RNDArgument RNDContextArgument;
FOUNDATION_EXPORT RNDArgument RNDBindingSelectorArgument;
FOUNDATION_EXPORT RNDArgument RNDUnbindingSelectorArgument;
FOUNDATION_EXPORT RNDArgument RNDActionSelectorArgument;
FOUNDATION_EXPORT RNDArgument RNDBinderArgument;
FOUNDATION_EXPORT RNDArgument RNDObserverArgument;
FOUNDATION_EXPORT RNDArgument RNDIterationArgument;
FOUNDATION_EXPORT RNDArgument RNDPositionArgument;
FOUNDATION_EXPORT RNDArgument RNDBinderObjectValue;

#pragma mark - RNDNotifications
typedef NSString * const RNDBindingNotifications NS_STRING_ENUM;
FOUNDATION_EXPORT RNDBindingNotifications RNDValueOfObserverObjectDidChange;
FOUNDATION_EXPORT RNDBindingNotifications RNDValueOfObservedObjectDidChange;


#pragma mark - RNDMarkers
typedef NSString * const RNDBindingMarker NS_STRING_ENUM;
FOUNDATION_EXPORT RNDBindingMarker RNDBindingMultipleValuesMarker;
FOUNDATION_EXPORT RNDBindingMarker RNDBindingNoSelectionMarker;
FOUNDATION_EXPORT RNDBindingMarker RNDBindingNotApplicableMarker;
FOUNDATION_EXPORT RNDBindingMarker RNDBindingNullValueMarker;
FOUNDATION_EXPORT RNDBindingMarker RNDBindingLoadingMarker;
FOUNDATION_EXPORT RNDBindingMarker RNDBindingLoadingErrorMarker;
FOUNDATION_EXPORT RNDBindingMarker RNDBindingResourceNotFoundMarker;
FOUNDATION_EXPORT RNDBindingMarker RNDBindingManifestNotFoundErrorMarker;
FOUNDATION_EXPORT RNDBindingMarker RNDBindingBinderSetNotFoundMarker;
FOUNDATION_EXPORT RNDBindingMarker RNDBindingUnboundErrorMarker;
FOUNDATION_EXPORT RNDBindingMarker RNDBindingInvalidKeyPathMarker;
FOUNDATION_EXPORT RNDBindingMarker RNDBindingBinderNotFoundMarker;
FOUNDATION_EXPORT RNDBindingMarker RNDBindingInvalidArgumentMarker;

FOUNDATION_EXPORT BOOL RNDIsControllerMarker(__nullable id object);

#pragma mark - RNDResouceInfoKeys
typedef NSString * const RNDResourceInfoKey NS_STRING_ENUM;
FOUNDATION_EXPORT RNDResourceInfoKey RNDResourceInfoLoadingTypeKey;
FOUNDATION_EXPORT RNDResourceInfoKey RNDResourceInfoResourceTypeKey;

#pragma mark - RNDResourceInfoOptions
typedef NSString * const RNDResourceInfoOption NS_STRING_ENUM;
FOUNDATION_EXPORT RNDResourceInfoOption RNDResourceInfoSynchronousOption;
FOUNDATION_EXPORT RNDResourceInfoOption RNDResourceInfoAsynchronousOption;

#pragma mark - RNDBindingType
// Identifies the binding behavior.
typedef NSString * const RNDBinderType NS_STRING_ENUM;
FOUNDATION_EXPORT RNDBinderType RNDBindingTypeSimpleValue; // Binds to observer and observed
FOUNDATION_EXPORT RNDBinderType RNDBindingTypeSimpleValueReadOnly; // Binds to observed
FOUNDATION_EXPORT RNDBinderType RNDBindingTypeSimpleValueWriteOnly; // Binds to observer
FOUNDATION_EXPORT RNDBinderType RNDBindingTypeMultiValueAND; // Binds to observed
FOUNDATION_EXPORT RNDBinderType RNDBindingTypeMultiValueOR; // Binds to observed
FOUNDATION_EXPORT RNDBinderType RNDBindingTypeMultiValueArgument; // Does not bind to either
FOUNDATION_EXPORT RNDBinderType RNDBindingTypeMultiValueWithPattern; // Binds to observed
FOUNDATION_EXPORT RNDBinderType RNDBindingTypeMultiValuePredicate; // Does not bind to either

#pragma mark - RNDBindingInfoKey
typedef NSString * const RNDBindingInfoKey NS_STRING_ENUM;
FOUNDATION_EXPORT RNDBindingInfoKey RNDBindingInfoTypeKey;
FOUNDATION_EXPORT RNDBindingInfoKey RNDBindingInfoOptionsKey;
FOUNDATION_EXPORT RNDBindingInfoKey RNDBindingInfoNameKey;
FOUNDATION_EXPORT RNDBindingInfoKey RNDBindingInfoExclusionsKey;
FOUNDATION_EXPORT RNDBindingInfoKey RNDBindingInfoRequirementsKey;
FOUNDATION_EXPORT RNDBindingInfoKey RNDBindingInfoValueTypeKey;
FOUNDATION_EXPORT RNDBindingInfoKey RNDBindingInfoValueClassKey;
FOUNDATION_EXPORT RNDBindingInfoKey RNDBindingInfoDefaultValueKey;
FOUNDATION_EXPORT RNDBindingInfoKey RNDBindingInfoObservedObjectKey;
FOUNDATION_EXPORT RNDBindingInfoKey RNDBindingInfoObservedKeyPathKey;
FOUNDATION_EXPORT RNDBindingInfoKey RNDBindingInfoGroupKey;
FOUNDATION_EXPORT RNDBindingInfoKey RNDBindingInfoBinderClassKey;
FOUNDATION_EXPORT RNDBindingInfoKey RNDBindingInfoBindingClassKey;


#pragma mark - RNDBindingInfoGroupType
typedef NSString * const RNDBinderInfoGroupType;
FOUNDATION_EXPORT RNDBinderInfoGroupType RNDBindingInfoGroupValueType;
FOUNDATION_EXPORT RNDBinderInfoGroupType RNDBindingInfoGroupValueWithPatternType;
FOUNDATION_EXPORT RNDBinderInfoGroupType RNDBindingInfoGroupAvailabilityType;
FOUNDATION_EXPORT RNDBinderInfoGroupType RNDBindingInfoGroupFontType;
FOUNDATION_EXPORT RNDBinderInfoGroupType RNDBindingInfoGroupParametersType;
FOUNDATION_EXPORT RNDBinderInfoGroupType RNDBindingInfoGroupTextColorType;
FOUNDATION_EXPORT RNDBinderInfoGroupType RNDBindingInfoGroupTitleType;
FOUNDATION_EXPORT RNDBinderInfoGroupType RNDBindingInfoGroupTitleWithPatternType;
FOUNDATION_EXPORT RNDBinderInfoGroupType RNDBindingInfoGroupControllerContentType;
FOUNDATION_EXPORT RNDBinderInfoGroupType RNDBindingInfoGroupControllerContentWithParametersType;
FOUNDATION_EXPORT RNDBinderInfoGroupType RNDBindingInfoGroupActionInvocationType;
FOUNDATION_EXPORT RNDBinderInfoGroupType RNDBindingInfoGroupTableContentType;
FOUNDATION_EXPORT RNDBinderInfoGroupType RNDBindingInfoGroupTabViewItemSelectionType;
FOUNDATION_EXPORT RNDBinderInfoGroupType RNDBindingInfoGroupSegmentSelectionType;
FOUNDATION_EXPORT RNDBinderInfoGroupType RNDBindingInfoGroupSearchType;

#pragma mark - RNDBindingValueType
typedef NSString * const RNDBindingValueType;
FOUNDATION_EXPORT RNDBindingValueType RNDBindingValueInt8Type;
FOUNDATION_EXPORT RNDBindingValueType RNDBindingValueInt16Type;
FOUNDATION_EXPORT RNDBindingValueType RNDBindingValueInt32Type;
FOUNDATION_EXPORT RNDBindingValueType RNDBindingValueInt64Type;
FOUNDATION_EXPORT RNDBindingValueType RNDBindingValueFloatType;
FOUNDATION_EXPORT RNDBindingValueType RNDBindingValueDoubleType;
FOUNDATION_EXPORT RNDBindingValueType RNDBindingValueStringType;
FOUNDATION_EXPORT RNDBindingValueType RNDBindingValueUUIDType;
FOUNDATION_EXPORT RNDBindingValueType RNDBindingValueURLType;
FOUNDATION_EXPORT RNDBindingValueType RNDBindingValueDateType;
FOUNDATION_EXPORT RNDBindingValueType RNDBindingValueBooleanType;
FOUNDATION_EXPORT RNDBindingValueType RNDBindingValueDecimalType;
FOUNDATION_EXPORT RNDBindingValueType RNDBindingValueBinaryType;
FOUNDATION_EXPORT RNDBindingValueType RNDBindingValueUndefinedType;
FOUNDATION_EXPORT RNDBindingValueType RNDBindingValueObjectIDType;
FOUNDATION_EXPORT RNDBindingValueType RNDBindingValueTransformableType;


#pragma mark - RNDBindingKeyPathComponent
typedef NSString * const RNDBindingKeyPathComponent NS_STRING_ENUM;
FOUNDATION_EXPORT RNDBindingKeyPathComponent RNDBindingCurrentSelectionKeyPathComponent;
FOUNDATION_EXPORT RNDBindingKeyPathComponent RNDBindingSelectedObjectsKeyPathComponent;
FOUNDATION_EXPORT RNDBindingKeyPathComponent RNDBindingArrangedObjectsKeyPathComponent;
FOUNDATION_EXPORT RNDBindingKeyPathComponent RNDBindingContentObjectKeyPathComponent;

#pragma mark - RNDBindingName
typedef NSString * const RNDBinderName NS_EXTENSIBLE_STRING_ENUM;
FOUNDATION_EXPORT RNDBinderName RNDAlignmentBindingName;
FOUNDATION_EXPORT RNDBinderName RNDAlternateImageBindingName;
FOUNDATION_EXPORT RNDBinderName RNDAlternateTitleBindingName;
FOUNDATION_EXPORT RNDBinderName RNDAnimateBindingName;
FOUNDATION_EXPORT RNDBinderName RNDAnimationDelayBindingName;
FOUNDATION_EXPORT RNDBinderName RNDArgumentBindingName;
FOUNDATION_EXPORT RNDBinderName RNDAttributedStringBindingName;
FOUNDATION_EXPORT RNDBinderName RNDContentArrayBindingName;
FOUNDATION_EXPORT RNDBinderName RNDContentArrayForMultipleSelectionBindingName;
FOUNDATION_EXPORT RNDBinderName RNDContentBindingName;
FOUNDATION_EXPORT RNDBinderName RNDContentDictionaryBindingName;
FOUNDATION_EXPORT RNDBinderName RNDContentHeightBindingName;
FOUNDATION_EXPORT RNDBinderName RNDContentObjectBindingName;
FOUNDATION_EXPORT RNDBinderName RNDContentObjectsBindingName;
FOUNDATION_EXPORT RNDBinderName RNDContentSetBindingName;
FOUNDATION_EXPORT RNDBinderName RNDContentValuesBindingName;
FOUNDATION_EXPORT RNDBinderName RNDContentWidthBindingName;
FOUNDATION_EXPORT RNDBinderName RNDCriticalValueBindingName;
FOUNDATION_EXPORT RNDBinderName RNDDataBindingName;
FOUNDATION_EXPORT RNDBinderName RNDDisplayPatternTitleBindingName;
FOUNDATION_EXPORT RNDBinderName RNDDisplayPatternValueBindingName;
FOUNDATION_EXPORT RNDBinderName RNDDocumentEditedBindingName;
FOUNDATION_EXPORT RNDBinderName RNDDoubleClickArgumentBindingName;
FOUNDATION_EXPORT RNDBinderName RNDDoubleClickTargetBindingName;
FOUNDATION_EXPORT RNDBinderName RNDEditableBindingName;
FOUNDATION_EXPORT RNDBinderName RNDEnabledBindingName;
FOUNDATION_EXPORT RNDBinderName RNDExcludedKeysBindingName;
FOUNDATION_EXPORT RNDBinderName RNDFilterPredicateBindingName;
FOUNDATION_EXPORT RNDBinderName RNDFontBindingName;
FOUNDATION_EXPORT RNDBinderName RNDFontBoldBindingName;
FOUNDATION_EXPORT RNDBinderName RNDFontFamilyNameBindingName;
FOUNDATION_EXPORT RNDBinderName RNDFontItalicBindingName;
FOUNDATION_EXPORT RNDBinderName RNDFontNameBindingName;
FOUNDATION_EXPORT RNDBinderName RNDFontSizeBindingName;
FOUNDATION_EXPORT RNDBinderName RNDHeaderTitleBindingName;
FOUNDATION_EXPORT RNDBinderName RNDHiddenBindingName;
FOUNDATION_EXPORT RNDBinderName RNDImageBindingName;
FOUNDATION_EXPORT RNDBinderName RNDIncludedKeysBindingName;
FOUNDATION_EXPORT RNDBinderName RNDInitialKeyBindingName;
FOUNDATION_EXPORT RNDBinderName RNDInitialValueBindingName;
FOUNDATION_EXPORT RNDBinderName RNDIsIndeterminateBindingName;
FOUNDATION_EXPORT RNDBinderName RNDLabelBindingName;
FOUNDATION_EXPORT RNDBinderName RNDLocalizedKeyDictionaryBindingName;
FOUNDATION_EXPORT RNDBinderName RNDManagedObjectContextBindingName;
FOUNDATION_EXPORT RNDBinderName RNDMaximumRecentsBindingName;
FOUNDATION_EXPORT RNDBinderName RNDMaxValueBindingName;
FOUNDATION_EXPORT RNDBinderName RNDMaxWidthBindingName;
FOUNDATION_EXPORT RNDBinderName RNDMinValueBindingName;
FOUNDATION_EXPORT RNDBinderName RNDMinWidthBindingName;
FOUNDATION_EXPORT RNDBinderName RNDMixedStateImageBindingName;
FOUNDATION_EXPORT RNDBinderName RNDOffStateImageBindingName;
FOUNDATION_EXPORT RNDBinderName RNDOnStateImageBindingName;
FOUNDATION_EXPORT RNDBinderName RNDPositioningRectBindingName;
FOUNDATION_EXPORT RNDBinderName RNDPredicateBindingName;
FOUNDATION_EXPORT RNDBinderName RNDRecentSearchesBindingName;
FOUNDATION_EXPORT RNDBinderName RNDRepresentedFilenameBindingName;
FOUNDATION_EXPORT RNDBinderName RNDRowHeightBindingName;
FOUNDATION_EXPORT RNDBinderName RNDSelectedIdentifierBindingName;
FOUNDATION_EXPORT RNDBinderName RNDSelectedIndexBindingName;
FOUNDATION_EXPORT RNDBinderName RNDSelectedLabelBindingName;
FOUNDATION_EXPORT RNDBinderName RNDSelectedObjectBindingName;
FOUNDATION_EXPORT RNDBinderName RNDSelectedObjectsBindingName;
FOUNDATION_EXPORT RNDBinderName RNDSelectedTagBindingName;
FOUNDATION_EXPORT RNDBinderName RNDSelectedValueBindingName;
FOUNDATION_EXPORT RNDBinderName RNDSelectedValuesBindingName;
FOUNDATION_EXPORT RNDBinderName RNDSelectionIndexesBindingName;
FOUNDATION_EXPORT RNDBinderName RNDSelectionIndexPathsBindingName;
FOUNDATION_EXPORT RNDBinderName RNDSortDescriptorsBindingName;
FOUNDATION_EXPORT RNDBinderName RNDTargetBindingName;
FOUNDATION_EXPORT RNDBinderName RNDTextColorBindingName;
FOUNDATION_EXPORT RNDBinderName RNDTitleBindingName;
FOUNDATION_EXPORT RNDBinderName RNDToolTipBindingName;
FOUNDATION_EXPORT RNDBinderName RNDTransparentBindingName;
FOUNDATION_EXPORT RNDBinderName RNDValueBindingName;
FOUNDATION_EXPORT RNDBinderName RNDValuePathBindingName;
FOUNDATION_EXPORT RNDBinderName RNDValueURLBindingName;
FOUNDATION_EXPORT RNDBinderName RNDVisibleBindingName;
FOUNDATION_EXPORT RNDBinderName RNDWarningValueBindingName;
FOUNDATION_EXPORT RNDBinderName RNDWidthBindingName;

#pragma mark - RNDBindingOption
typedef NSString * const RNDBindingOption NS_STRING_ENUM;
FOUNDATION_EXPORT RNDBindingOption RNDAllowsEditingMultipleValuesSelectionBindingOption;
FOUNDATION_EXPORT RNDBindingOption RNDAllowsNullArgumentBindingOption;
FOUNDATION_EXPORT RNDBindingOption RNDAlwaysPresentsApplicationModalAlertsBindingOption;
FOUNDATION_EXPORT RNDBindingOption RNDConditionallySetsEditableBindingOption;
FOUNDATION_EXPORT RNDBindingOption RNDConditionallySetsEnabledBindingOption;
FOUNDATION_EXPORT RNDBindingOption RNDConditionallySetsHiddenBindingOption;
FOUNDATION_EXPORT RNDBindingOption RNDContinuouslyUpdatesValueBindingOption;
FOUNDATION_EXPORT RNDBindingOption RNDCreatesSortDescriptorBindingOption;
FOUNDATION_EXPORT RNDBindingOption RNDDeletesObjectsOnRemoveBindingsOption;
FOUNDATION_EXPORT RNDBindingOption RNDDisplayNameBindingOption;
FOUNDATION_EXPORT RNDBindingOption RNDDisplayPatternBindingOption;
FOUNDATION_EXPORT RNDBindingOption RNDContentPlacementTagBindingOption;
FOUNDATION_EXPORT RNDBindingOption RNDHandlesContentAsCompoundValueBindingOption;
FOUNDATION_EXPORT RNDBindingOption RNDInsertsNullPlaceholderBindingOption;
FOUNDATION_EXPORT RNDBindingOption RNDInvokesSeparatelyWithArrayObjectsBindingOption;
FOUNDATION_EXPORT RNDBindingOption RNDMultipleValuesPlaceholderBindingOption;
FOUNDATION_EXPORT RNDBindingOption RNDNoSelectionPlaceholderBindingOption;
FOUNDATION_EXPORT RNDBindingOption RNDNotApplicablePlaceholderBindingOption;
FOUNDATION_EXPORT RNDBindingOption RNDNullPlaceholderBindingOption;
FOUNDATION_EXPORT RNDBindingOption RNDRaisesForNotApplicableKeysBindingOption;
FOUNDATION_EXPORT RNDBindingOption RNDPredicateFormatBindingOption;
FOUNDATION_EXPORT RNDBindingOption RNDSelectorNameBindingOption;
FOUNDATION_EXPORT RNDBindingOption RNDSelectsAllWhenSettingContentBindingOption;
FOUNDATION_EXPORT RNDBindingOption RNDValidatesImmediatelyBindingOption;
FOUNDATION_EXPORT RNDBindingOption RNDValueTransformerNameBindingOption;
FOUNDATION_EXPORT RNDBindingOption RNDValueTransformerBindingOption;
FOUNDATION_EXPORT RNDBindingOption RNDArgumentPositionBindingOption;
FOUNDATION_EXPORT RNDBindingOption RNDActionInvocationBindingOption;
FOUNDATION_EXPORT RNDBindingOption RNDMonitorsObservedObjectOption;
FOUNDATION_EXPORT RNDBindingOption RNDArgumentNameOption;

NS_ASSUME_NONNULL_END
