//
//  RNDBindingConstants.h
//  RNDKit
//
//  Created by Erikheath Thomas on 10/20/17.
//  Copyright © 2017 Curated Cocoa LLC. All rights reserved.
//

#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

#pragma mark - RNDProcessorQueueNames
typedef NSString * RNDProcessorQueueName NS_STRING_ENUM;
extern RNDProcessorQueueName RNDForwardProcessingQueue;
extern RNDProcessorQueueName RNDReverseProcessingQueue;

#pragma mark - RNDArgumentNames
typedef NSString * RNDArgument NS_STRING_ENUM;
extern RNDArgument RNDEventArgument;
extern RNDArgument RNDSenderArgument;
extern RNDArgument RNDContextArgument;
extern RNDArgument RNDBindingSelectorArgument;
extern RNDArgument RNDUnbindingSelectorArgument;
extern RNDArgument RNDActionSelectorArgument;
extern RNDArgument RNDBinderArgument;
extern RNDArgument RNDObserverArgument;

#pragma mark - RNDNotifications
typedef NSString * RNDBindingNotifications NS_STRING_ENUM;
extern RNDBindingNotifications RNDValueOfObserverObjectDidChange;
extern RNDBindingNotifications RNDValueOfObservedObjectDidChange;


#pragma mark - RNDMarkers
typedef NSString * RNDBindingMarker NS_STRING_ENUM;
extern RNDBindingMarker RNDBindingMultipleValuesMarker;
extern RNDBindingMarker RNDBindingNoSelectionMarker;
extern RNDBindingMarker RNDBindingNotApplicableMarker;
extern RNDBindingMarker RNDBindingNullValueMarker;

extern BOOL RNDIsControllerMarker(__nullable id object);


#pragma mark - RNDBindingType
// Identifies the binding behavior.
typedef NSString * RNDBinderType NS_STRING_ENUM;
extern RNDBinderType RNDBindingTypeSimpleValue; // Binds to observer and observed
extern RNDBinderType RNDBindingTypeSimpleValueReadOnly; // Binds to observed
extern RNDBinderType RNDBindingTypeSimpleValueWriteOnly; // Binds to observer
extern RNDBinderType RNDBindingTypeMultiValueAND; // Binds to observed
extern RNDBinderType RNDBindingTypeMultiValueOR; // Binds to observed
extern RNDBinderType RNDBindingTypeMultiValueArgument; // Does not bind to either
extern RNDBinderType RNDBindingTypeMultiValueWithPattern; // Binds to observed
extern RNDBinderType RNDBindingTypeMultiValuePredicate; // Does not bind to either

#pragma mark - RNDBindingInfoKey
typedef NSString * RNDBindingInfoKey NS_STRING_ENUM;
extern RNDBindingInfoKey RNDBindingInfoTypeKey;
extern RNDBindingInfoKey RNDBindingInfoOptionsKey;
extern RNDBindingInfoKey RNDBindingInfoNameKey;
extern RNDBindingInfoKey RNDBindingInfoExclusionsKey;
extern RNDBindingInfoKey RNDBindingInfoRequirementsKey;
extern RNDBindingInfoKey RNDBindingInfoValueTypeKey;
extern RNDBindingInfoKey RNDBindingInfoValueClassKey;
extern RNDBindingInfoKey RNDBindingInfoDefaultValueKey;
extern RNDBindingInfoKey RNDBindingInfoObservedObjectKey;
extern RNDBindingInfoKey RNDBindingInfoObservedKeyPathKey;
extern RNDBindingInfoKey RNDBindingInfoGroupKey;
extern RNDBindingInfoKey RNDBindingInfoBinderClassKey;
extern RNDBindingInfoKey RNDBindingInfoBindingClassKey;


#pragma mark - RNDBindingInfoGroupType
typedef NSString * RNDBinderInfoGroupType;
extern RNDBinderInfoGroupType RNDBindingInfoGroupValueType;
extern RNDBinderInfoGroupType RNDBindingInfoGroupValueWithPatternType;
extern RNDBinderInfoGroupType RNDBindingInfoGroupAvailabilityType;
extern RNDBinderInfoGroupType RNDBindingInfoGroupFontType;
extern RNDBinderInfoGroupType RNDBindingInfoGroupParametersType;
extern RNDBinderInfoGroupType RNDBindingInfoGroupTextColorType;
extern RNDBinderInfoGroupType RNDBindingInfoGroupTitleType;
extern RNDBinderInfoGroupType RNDBindingInfoGroupTitleWithPatternType;
extern RNDBinderInfoGroupType RNDBindingInfoGroupControllerContentType;
extern RNDBinderInfoGroupType RNDBindingInfoGroupControllerContentWithParametersType;
extern RNDBinderInfoGroupType RNDBindingInfoGroupActionInvocationType;
extern RNDBinderInfoGroupType RNDBindingInfoGroupTableContentType;
extern RNDBinderInfoGroupType RNDBindingInfoGroupTabViewItemSelectionType;
extern RNDBinderInfoGroupType RNDBindingInfoGroupSegmentSelectionType;
extern RNDBinderInfoGroupType RNDBindingInfoGroupSearchType;

#pragma mark - RNDBindingValueType
typedef NSString * RNDBindingValueType;
extern RNDBindingValueType RNDBindingValueInt8Type;
extern RNDBindingValueType RNDBindingValueInt16Type;
extern RNDBindingValueType RNDBindingValueInt32Type;
extern RNDBindingValueType RNDBindingValueInt64Type;
extern RNDBindingValueType RNDBindingValueFloatType;
extern RNDBindingValueType RNDBindingValueDoubleType;
extern RNDBindingValueType RNDBindingValueStringType;
extern RNDBindingValueType RNDBindingValueUUIDType;
extern RNDBindingValueType RNDBindingValueURLType;
extern RNDBindingValueType RNDBindingValueDateType;
extern RNDBindingValueType RNDBindingValueBooleanType;
extern RNDBindingValueType RNDBindingValueDecimalType;
extern RNDBindingValueType RNDBindingValueBinaryType;
extern RNDBindingValueType RNDBindingValueUndefinedType;
extern RNDBindingValueType RNDBindingValueObjectIDType;
extern RNDBindingValueType RNDBindingValueTransformableType;


#pragma mark - RNDBindingKeyPathComponent
typedef NSString * RNDBindingKeyPathComponent NS_STRING_ENUM;
extern RNDBindingKeyPathComponent RNDBindingCurrentSelectionKeyPathComponent;
extern RNDBindingKeyPathComponent RNDBindingSelectedObjectsKeyPathComponent;
extern RNDBindingKeyPathComponent RNDBindingArrangedObjectsKeyPathComponent;
extern RNDBindingKeyPathComponent RNDBindingContentObjectKeyPathComponent;

#pragma mark - RNDBindingName
typedef NSString * RNDBinderName NS_EXTENSIBLE_STRING_ENUM;
extern RNDBinderName RNDAlignmentBindingName;
extern RNDBinderName RNDAlternateImageBindingName;
extern RNDBinderName RNDAlternateTitleBindingName;
extern RNDBinderName RNDAnimateBindingName;
extern RNDBinderName RNDAnimationDelayBindingName;
extern RNDBinderName RNDArgumentBindingName;
extern RNDBinderName RNDAttributedStringBindingName;
extern RNDBinderName RNDContentArrayBindingName;
extern RNDBinderName RNDContentArrayForMultipleSelectionBindingName;
extern RNDBinderName RNDContentBindingName;
extern RNDBinderName RNDContentDictionaryBindingName;
extern RNDBinderName RNDContentHeightBindingName;
extern RNDBinderName RNDContentObjectBindingName;
extern RNDBinderName RNDContentObjectsBindingName;
extern RNDBinderName RNDContentSetBindingName;
extern RNDBinderName RNDContentValuesBindingName;
extern RNDBinderName RNDContentWidthBindingName;
extern RNDBinderName RNDCriticalValueBindingName;
extern RNDBinderName RNDDataBindingName;
extern RNDBinderName RNDDisplayPatternTitleBindingName;
extern RNDBinderName RNDDisplayPatternValueBindingName;
extern RNDBinderName RNDDocumentEditedBindingName;
extern RNDBinderName RNDDoubleClickArgumentBindingName;
extern RNDBinderName RNDDoubleClickTargetBindingName;
extern RNDBinderName RNDEditableBindingName;
extern RNDBinderName RNDEnabledBindingName;
extern RNDBinderName RNDExcludedKeysBindingName;
extern RNDBinderName RNDFilterPredicateBindingName;
extern RNDBinderName RNDFontBindingName;
extern RNDBinderName RNDFontBoldBindingName;
extern RNDBinderName RNDFontFamilyNameBindingName;
extern RNDBinderName RNDFontItalicBindingName;
extern RNDBinderName RNDFontNameBindingName;
extern RNDBinderName RNDFontSizeBindingName;
extern RNDBinderName RNDHeaderTitleBindingName;
extern RNDBinderName RNDHiddenBindingName;
extern RNDBinderName RNDImageBindingName;
extern RNDBinderName RNDIncludedKeysBindingName;
extern RNDBinderName RNDInitialKeyBindingName;
extern RNDBinderName RNDInitialValueBindingName;
extern RNDBinderName RNDIsIndeterminateBindingName;
extern RNDBinderName RNDLabelBindingName;
extern RNDBinderName RNDLocalizedKeyDictionaryBindingName;
extern RNDBinderName RNDManagedObjectContextBindingName;
extern RNDBinderName RNDMaximumRecentsBindingName;
extern RNDBinderName RNDMaxValueBindingName;
extern RNDBinderName RNDMaxWidthBindingName;
extern RNDBinderName RNDMinValueBindingName;
extern RNDBinderName RNDMinWidthBindingName;
extern RNDBinderName RNDMixedStateImageBindingName;
extern RNDBinderName RNDOffStateImageBindingName;
extern RNDBinderName RNDOnStateImageBindingName;
extern RNDBinderName RNDPositioningRectBindingName;
extern RNDBinderName RNDPredicateBindingName;
extern RNDBinderName RNDRecentSearchesBindingName;
extern RNDBinderName RNDRepresentedFilenameBindingName;
extern RNDBinderName RNDRowHeightBindingName;
extern RNDBinderName RNDSelectedIdentifierBindingName;
extern RNDBinderName RNDSelectedIndexBindingName;
extern RNDBinderName RNDSelectedLabelBindingName;
extern RNDBinderName RNDSelectedObjectBindingName;
extern RNDBinderName RNDSelectedObjectsBindingName;
extern RNDBinderName RNDSelectedTagBindingName;
extern RNDBinderName RNDSelectedValueBindingName;
extern RNDBinderName RNDSelectedValuesBindingName;
extern RNDBinderName RNDSelectionIndexesBindingName;
extern RNDBinderName RNDSelectionIndexPathsBindingName;
extern RNDBinderName RNDSortDescriptorsBindingName;
extern RNDBinderName RNDTargetBindingName;
extern RNDBinderName RNDTextColorBindingName;
extern RNDBinderName RNDTitleBindingName;
extern RNDBinderName RNDToolTipBindingName;
extern RNDBinderName RNDTransparentBindingName;
extern RNDBinderName RNDValueBindingName;
extern RNDBinderName RNDValuePathBindingName;
extern RNDBinderName RNDValueURLBindingName;
extern RNDBinderName RNDVisibleBindingName;
extern RNDBinderName RNDWarningValueBindingName;
extern RNDBinderName RNDWidthBindingName;

#pragma mark - RNDBindingOption
typedef NSString * RNDBindingOption NS_STRING_ENUM;
extern RNDBindingOption RNDAllowsEditingMultipleValuesSelectionBindingOption;
extern RNDBindingOption RNDAllowsNullArgumentBindingOption;
extern RNDBindingOption RNDAlwaysPresentsApplicationModalAlertsBindingOption;
extern RNDBindingOption RNDConditionallySetsEditableBindingOption;
extern RNDBindingOption RNDConditionallySetsEnabledBindingOption;
extern RNDBindingOption RNDConditionallySetsHiddenBindingOption;
extern RNDBindingOption RNDContinuouslyUpdatesValueBindingOption;
extern RNDBindingOption RNDCreatesSortDescriptorBindingOption;
extern RNDBindingOption RNDDeletesObjectsOnRemoveBindingsOption;
extern RNDBindingOption RNDDisplayNameBindingOption;
extern RNDBindingOption RNDDisplayPatternBindingOption;
extern RNDBindingOption RNDContentPlacementTagBindingOption;
extern RNDBindingOption RNDHandlesContentAsCompoundValueBindingOption;
extern RNDBindingOption RNDInsertsNullPlaceholderBindingOption;
extern RNDBindingOption RNDInvokesSeparatelyWithArrayObjectsBindingOption;
extern RNDBindingOption RNDMultipleValuesPlaceholderBindingOption;
extern RNDBindingOption RNDNoSelectionPlaceholderBindingOption;
extern RNDBindingOption RNDNotApplicablePlaceholderBindingOption;
extern RNDBindingOption RNDNullPlaceholderBindingOption;
extern RNDBindingOption RNDRaisesForNotApplicableKeysBindingOption;
extern RNDBindingOption RNDPredicateFormatBindingOption;
extern RNDBindingOption RNDSelectorNameBindingOption;
extern RNDBindingOption RNDSelectsAllWhenSettingContentBindingOption;
extern RNDBindingOption RNDValidatesImmediatelyBindingOption;
extern RNDBindingOption RNDValueTransformerNameBindingOption;
extern RNDBindingOption RNDValueTransformerBindingOption;
extern RNDBindingOption RNDArgumentPositionBindingOption;
extern RNDBindingOption RNDActionInvocationBindingOption;
extern RNDBindingOption RNDMonitorsObservedObjectOption;
extern RNDBindingOption RNDArgumentNameOption;

NS_ASSUME_NONNULL_END
