//
//  RNDBindingConstants.h
//  RNDKit
//
//  Created by Erikheath Thomas on 10/20/17.
//  Copyright © 2017 Curated Cocoa LLC. All rights reserved.
//

#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

#pragma mark - RNDMarkers
typedef NSString * RNDBindingMarker NS_STRING_ENUM;
extern RNDBindingMarker RNDBindingMultipleValuesMarker;
extern RNDBindingMarker RNDBindingNoSelectionMarker;
extern RNDBindingMarker RNDBindingNotApplicableMarker;

extern BOOL RNDIsControllerMarker(__nullable id object);


#pragma mark - RNDBindingType
// Identifies the binding behavior.
typedef NSString * RNDBindingType NS_STRING_ENUM;
extern RNDBindingType RNDBindingTypeSimpleValue; // Binds to observer and observed
extern RNDBindingType RNDBindingTypeSimpleValueReadOnly; // Binds to observed
extern RNDBindingType RNDBindingTypeSimpleValueWriteOnly; // Binds to observer
extern RNDBindingType RNDBindingTypeMultiValueAND; // Binds to observed
extern RNDBindingType RNDBindingTypeMultiValueOR; // Binds to observed
extern RNDBindingType RNDBindingTypeMultiValueArgument; // Does not bind to either
extern RNDBindingType RNDBindingTypeMultiValueWithPattern; // Binds to observed
extern RNDBindingType RNDBindingTypeMultiValuePredicate; // Does not bind to either

#pragma mark - RNDBindingInfoKey
typedef NSString * RNDBindingInfoKey NS_STRING_ENUM;
extern RNDBindingInfoKey RNDBindingInfoTypeKey;
extern RNDBindingInfoKey RNDBindingInfoOptionsKey;
extern RNDBindingInfoKey RNDBindingInfoNameKey;
extern RNDBindingInfoKey RNDBindingInfoExclusionsKey;
extern RNDBindingInfoKey RNDBindingInfoRequirementsKey;
extern RNDBindingInfoKey RNDBindingInfoValueTypeKey;
extern RNDBindingInfoKey RNDBindingInfoValueClassKey;
extern RNDBindingInfoKey RNDBindingInfoDefaultValueKey;
extern RNDBindingInfoKey RNDBindingInfoObservedObjectKey;
extern RNDBindingInfoKey RNDBindingInfoObservedKeyPathKey;
extern RNDBindingInfoKey RNDBindingInfoGroupKey;
extern RNDBindingInfoKey RNDBindingInfoBinderClassKey;
extern RNDBindingInfoKey RNDBindingInfoBindingClassKey;


#pragma mark - RNDBindingInfoGroupType
typedef NSString * RNDBindingInfoGroupType;
extern RNDBindingInfoGroupType RNDBindingInfoGroupValueType;
extern RNDBindingInfoGroupType RNDBindingInfoGroupValueWithPatternType;
extern RNDBindingInfoGroupType RNDBindingInfoGroupAvailabilityType;
extern RNDBindingInfoGroupType RNDBindingInfoGroupFontType;
extern RNDBindingInfoGroupType RNDBindingInfoGroupParametersType;
extern RNDBindingInfoGroupType RNDBindingInfoGroupTextColorType;
extern RNDBindingInfoGroupType RNDBindingInfoGroupTitleType;
extern RNDBindingInfoGroupType RNDBindingInfoGroupTitleWithPatternType;
extern RNDBindingInfoGroupType RNDBindingInfoGroupControllerContentType;
extern RNDBindingInfoGroupType RNDBindingInfoGroupControllerContentWithParametersType;
extern RNDBindingInfoGroupType RNDBindingInfoGroupActionInvocationType;
extern RNDBindingInfoGroupType RNDBindingInfoGroupTableContentType;
extern RNDBindingInfoGroupType RNDBindingInfoGroupTabViewItemSelectionType;
extern RNDBindingInfoGroupType RNDBindingInfoGroupSegmentSelectionType;
extern RNDBindingInfoGroupType RNDBindingInfoGroupSearchType;

#pragma mark - RNDBindingValueType
typedef NSString * RNDBindingValueType;
extern RNDBindingValueType RNDBindingValueInt8Type;
extern RNDBindingValueType RNDBindingValueInt16Type;
extern RNDBindingValueType RNDBindingValueInt32Type;
extern RNDBindingValueType RNDBindingValueInt64Type;
extern RNDBindingValueType RNDBindingValueFloatType;
extern RNDBindingValueType RNDBindingValueDoubleType;
extern RNDBindingValueType RNDBindingValueStringType;
extern RNDBindingValueType RNDBindingValueUUIDType;
extern RNDBindingValueType RNDBindingValueURLType;
extern RNDBindingValueType RNDBindingValueDateType;
extern RNDBindingValueType RNDBindingValueBooleanType;
extern RNDBindingValueType RNDBindingValueDecimalType;
extern RNDBindingValueType RNDBindingValueBinaryType;
extern RNDBindingValueType RNDBindingValueUndefinedType;
extern RNDBindingValueType RNDBindingValueObjectIDType;
extern RNDBindingValueType RNDBindingValueTransformableType;


#pragma mark - RNDBindingKeyPathComponent
typedef NSString * RNDBindingKeyPathComponent NS_STRING_ENUM;
extern RNDBindingKeyPathComponent RNDBindingCurrentSelectionKeyPathComponent;
extern RNDBindingKeyPathComponent RNDBindingSelectedObjectsKeyPathComponent;
extern RNDBindingKeyPathComponent RNDBindingArrangedObjectsKeyPathComponent;
extern RNDBindingKeyPathComponent RNDBindingContentObjectKeyPathComponent;

#pragma mark - RNDBindingName
typedef NSString * RNDBindingName NS_EXTENSIBLE_STRING_ENUM;
extern RNDBindingName RNDAlignmentBindingName;
extern RNDBindingName RNDAlternateImageBindingName;
extern RNDBindingName RNDAlternateTitleBindingName;
extern RNDBindingName RNDAnimateBindingName;
extern RNDBindingName RNDAnimationDelayBindingName;
extern RNDBindingName RNDArgumentBindingName;
extern RNDBindingName RNDAttributedStringBindingName;
extern RNDBindingName RNDContentArrayBindingName;
extern RNDBindingName RNDContentArrayForMultipleSelectionBindingName;
extern RNDBindingName RNDContentBindingName;
extern RNDBindingName RNDContentDictionaryBindingName;
extern RNDBindingName RNDContentHeightBindingName;
extern RNDBindingName RNDContentObjectBindingName;
extern RNDBindingName RNDContentObjectsBindingName;
extern RNDBindingName RNDContentSetBindingName;
extern RNDBindingName RNDContentValuesBindingName;
extern RNDBindingName RNDContentWidthBindingName;
extern RNDBindingName RNDCriticalValueBindingName;
extern RNDBindingName RNDDataBindingName;
extern RNDBindingName RNDDisplayPatternTitleBindingName;
extern RNDBindingName RNDDisplayPatternValueBindingName;
extern RNDBindingName RNDDocumentEditedBindingName;
extern RNDBindingName RNDDoubleClickArgumentBindingName;
extern RNDBindingName RNDDoubleClickTargetBindingName;
extern RNDBindingName RNDEditableBindingName;
extern RNDBindingName RNDEnabledBindingName;
extern RNDBindingName RNDExcludedKeysBindingName;
extern RNDBindingName RNDFilterPredicateBindingName;
extern RNDBindingName RNDFontBindingName;
extern RNDBindingName RNDFontBoldBindingName;
extern RNDBindingName RNDFontFamilyNameBindingName;
extern RNDBindingName RNDFontItalicBindingName;
extern RNDBindingName RNDFontNameBindingName;
extern RNDBindingName RNDFontSizeBindingName;
extern RNDBindingName RNDHeaderTitleBindingName;
extern RNDBindingName RNDHiddenBindingName;
extern RNDBindingName RNDImageBindingName;
extern RNDBindingName RNDIncludedKeysBindingName;
extern RNDBindingName RNDInitialKeyBindingName;
extern RNDBindingName RNDInitialValueBindingName;
extern RNDBindingName RNDIsIndeterminateBindingName;
extern RNDBindingName RNDLabelBindingName;
extern RNDBindingName RNDLocalizedKeyDictionaryBindingName;
extern RNDBindingName RNDManagedObjectContextBindingName;
extern RNDBindingName RNDMaximumRecentsBindingName;
extern RNDBindingName RNDMaxValueBindingName;
extern RNDBindingName RNDMaxWidthBindingName;
extern RNDBindingName RNDMinValueBindingName;
extern RNDBindingName RNDMinWidthBindingName;
extern RNDBindingName RNDMixedStateImageBindingName;
extern RNDBindingName RNDOffStateImageBindingName;
extern RNDBindingName RNDOnStateImageBindingName;
extern RNDBindingName RNDPositioningRectBindingName;
extern RNDBindingName RNDPredicateBindingName;
extern RNDBindingName RNDRecentSearchesBindingName;
extern RNDBindingName RNDRepresentedFilenameBindingName;
extern RNDBindingName RNDRowHeightBindingName;
extern RNDBindingName RNDSelectedIdentifierBindingName;
extern RNDBindingName RNDSelectedIndexBindingName;
extern RNDBindingName RNDSelectedLabelBindingName;
extern RNDBindingName RNDSelectedObjectBindingName;
extern RNDBindingName RNDSelectedObjectsBindingName;
extern RNDBindingName RNDSelectedTagBindingName;
extern RNDBindingName RNDSelectedValueBindingName;
extern RNDBindingName RNDSelectedValuesBindingName;
extern RNDBindingName RNDSelectionIndexesBindingName;
extern RNDBindingName RNDSelectionIndexPathsBindingName;
extern RNDBindingName RNDSortDescriptorsBindingName;
extern RNDBindingName RNDTargetBindingName;
extern RNDBindingName RNDTextColorBindingName;
extern RNDBindingName RNDTitleBindingName;
extern RNDBindingName RNDToolTipBindingName;
extern RNDBindingName RNDTransparentBindingName;
extern RNDBindingName RNDValueBindingName;
extern RNDBindingName RNDValuePathBindingName;
extern RNDBindingName RNDValueURLBindingName;
extern RNDBindingName RNDVisibleBindingName;
extern RNDBindingName RNDWarningValueBindingName;
extern RNDBindingName RNDWidthBindingName;

#pragma mark - RNDBindingOption
typedef NSString * RNDBindingOption NS_STRING_ENUM;
extern RNDBindingOption RNDAllowsEditingMultipleValuesSelectionBindingOption;
extern RNDBindingOption RNDAllowsNullArgumentBindingOption;
extern RNDBindingOption RNDAlwaysPresentsApplicationModalAlertsBindingOption;
extern RNDBindingOption RNDConditionallySetsEditableBindingOption;
extern RNDBindingOption RNDConditionallySetsEnabledBindingOption;
extern RNDBindingOption RNDConditionallySetsHiddenBindingOption;
extern RNDBindingOption RNDContinuouslyUpdatesValueBindingOption;
extern RNDBindingOption RNDCreatesSortDescriptorBindingOption;
extern RNDBindingOption RNDDeletesObjectsOnRemoveBindingsOption;
extern RNDBindingOption RNDDisplayNameBindingOption;
extern RNDBindingOption RNDDisplayPatternBindingOption;
extern RNDBindingOption RNDContentPlacementTagBindingOption;
extern RNDBindingOption RNDHandlesContentAsCompoundValueBindingOption;
extern RNDBindingOption RNDInsertsNullPlaceholderBindingOption;
extern RNDBindingOption RNDInvokesSeparatelyWithArrayObjectsBindingOption;
extern RNDBindingOption RNDMultipleValuesPlaceholderBindingOption;
extern RNDBindingOption RNDNoSelectionPlaceholderBindingOption;
extern RNDBindingOption RNDNotApplicablePlaceholderBindingOption;
extern RNDBindingOption RNDNullPlaceholderBindingOption;
extern RNDBindingOption RNDRaisesForNotApplicableKeysBindingOption;
extern RNDBindingOption RNDPredicateFormatBindingOption;
extern RNDBindingOption RNDSelectorNameBindingOption;
extern RNDBindingOption RNDSelectsAllWhenSettingContentBindingOption;
extern RNDBindingOption RNDValidatesImmediatelyBindingOption;
extern RNDBindingOption RNDValueTransformerNameBindingOption;
extern RNDBindingOption RNDValueTransformerBindingOption;
extern RNDBindingOption RNDArgumentPositionBindingOption;
extern RNDBindingOption RNDActionInvocationBindingOption;

NS_ASSUME_NONNULL_END
